# Generated by Django 3.2.18 on 2023-03-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug'),
    ]

    operations = [

    ]
